genders=("male","female","others")
print(genders)
print(type(genders))
print(len(genders))
print(genders[0])
print(genders[1:3])
tuple=(1,2,3,4)
repeted_touple=(1,2)*3
print(repeted_touple)
print("male" in genders)
print(genders.index("male"))
gender=("male","female","others",(1,2,3))
print(gender)
s2=set((1,2,3))
print(type(s2))
s1={1,2,3}
print(s1)
s2={3,4,5}
s3=s1|s2
print(s3)
s3=s1&s2
print(s3)
s3=s1-s2
print(s3)
s1.add(4)
print(s1)
s1.discard(455)
print(s1)
a=s1.pop()
print(a)